name: Development Branch
on:
  push:
    branches:
      - master

jobs:
  compile_test:
    uses: ./.github/workflows/test.yml
  deploy_qax:
    needs: compile_test
    uses: ./.github/workflows/deploy.yml
    with:
      server-id: exchange-qax
      mvn-profile: qax
      exchange-org-id: 68ef9520-24e9-4cf2-b2f5-620025690913
      environment: qax
    secrets:
      EXCHANGE_USERNAME: ${{ secrets.EXCHANGE_USERNAME }}
      EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
  deploy_falcon_test:
    needs: compile_test
    uses: ./.github/workflows/deploy.yml
    with:
      server-id: exchange-test-falcon
      mvn-profile: test-ca
      exchange-org-id: 7e5913f6-95c2-4af4-8070-96bed4804c51
      environment: falcon-test
    secrets:
      EXCHANGE_USERNAME: ${{ secrets.EXCHANGE_USERNAME }}
      EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
      