name: Release branches workflow
on:
  push:
    branches:
      - 'release/**'


jobs:
  compile_test:
    uses: ./.github/workflows/test.yml
  deploy_qax:
    needs: compile_test
    uses: ./.github/workflows/deploy.yml
    with:
      server-id: exchange-qax
      mvn-profile: qax
      exchange-org-id: 68ef9520-24e9-4cf2-b2f5-620025690913
      environment: qax
    secrets:
      EXCHANGE_USERNAME: ${{ secrets.EXCHANGE_USERNAME }}
      EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
  deploy_prod_us:
    needs: deploy_qax
    uses: ./.github/workflows/deploy.yml
    with:
      server-id: exchange-prod-us
      mvn-profile: prod-us
      exchange-org-id: 68ef9520-24e9-4cf2-b2f5-620025690913
      environment: prod-us
    secrets:
      EXCHANGE_USERNAME: ${{ secrets.EXCHANGE_USERNAME }}
      EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
  deploy_prod_eu:
    needs: deploy_qax
    uses: ./.github/workflows/deploy.yml
    with:
      server-id: exchange-prod-eu
      mvn-profile: prod-eu
      exchange-org-id: e0b4a150-f59b-46d4-ad25-5d98f9deb24a
      environment: prod-eu
    secrets:
      EXCHANGE_USERNAME: ${{ secrets.EXCHANGE_USERNAME }}
      EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
  tag:
    name: "Tag Release"
    runs-on: ubuntu-latest
    needs: [deploy_prod_us, deploy_prod_eu]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Set version var
        id: version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      - name: Create and push tag
        run: |
          git tag "v${{ steps.version.outputs.version }}"

          git push origin "v${{ steps.version.outputs.version }}"